# Generated by Django 2.0.2 on 2018-02-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaillist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(max_length=250),
        ),
    ]
