# Generated by Django 2.0.2 on 2018-02-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaillist', '0002_auto_20180212_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
